builds:
  - binary: zenit
    env:
      - CGO_ENABLED=0
    targets:
      - linux_amd64
      - linux_arm64
      - darwin_amd64
      - darwin_arm64
    ldflags:
      - -s -w -X "github.com/debeando/zenit/command.BuildTime={{.Version}}"
archives:
  - name_template: '{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    replacements:
      darwin: mac
checksum:
  name_template: '{{ .ProjectName }}_checksums_{{ .Version }}.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  skip: true
