---
version: '3'

services:
  clickhouse:
    image: clickhouse
    build: clickhouse
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    ports:
      - "8123:8123"
    networks:
      default:
        ipv4_address: 172.20.1.2

  sandbox:
    image: sandbox
    build:
      context: ../
      dockerfile: docker/sandbox/Dockerfile
    networks:
      default:
        ipv4_address: 172.20.1.3

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.1.0/24
