---
version: '3'

services:
  clickhouse:
    image: clickhouse
    container_name: zenit_clickhouse
    build:
      context: ../
      dockerfile: docker/clickhouse/Dockerfile
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    ports:
      - "8123:8123"
    networks:
      default:
        ipv4_address: 172.20.1.2

  percona-server-primary:
    image: percona-server-primary
    container_name: zenit_percona_server_primary
    build:
      context: ../
      dockerfile: docker/percona-server/Dockerfile
    environment:
      - SERVER_ID=1
      - ZENIT_SLACK_TOKEN
      - ZENIT_SLACK_CHANNEL
    networks:
      default:
        ipv4_address: 172.20.1.3

  percona-server-secondary:
    image: percona-server-secondary
    container_name: zenit_percona_server_secondary
    build:
      context: ../
      dockerfile: docker/percona-server/Dockerfile
    environment:
      - SERVER_ID=2
      - ZENIT_SLACK_TOKEN
      - ZENIT_SLACK_CHANNEL
    networks:
      default:
        ipv4_address: 172.20.1.4
    depends_on:
      - percona-server-primary

  proxysql:
    image: proxysql
    container_name: zenit_proxysql
    build: proxysql
    build:
      context: ../
      dockerfile: docker/proxysql/Dockerfile
    networks:
      default:
        ipv4_address: 172.20.1.5
    environment:
      - ZENIT_SLACK_TOKEN
      - ZENIT_SLACK_CHANNEL
    depends_on:
      - percona-server-primary
      - percona-server-secondary

  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - "8083:8083"
      - "8086:8086"
      - "8090:8090"
    environment:
      - INFLUXDB_DATA_ENGINE=tsm1
      - INFLUXDB_REPORTING_DISABLED=false
    networks:
      default:
        ipv4_address: 172.20.1.6

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.1.0/24
