---
version: '3'

services:
  clickhouse:
    image: clickhouse
    build:
      context: ../
      dockerfile: docker/clickhouse/Dockerfile
    container_name: zenit_clickhouse
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    ports:
      - "8123:8123"
    networks:
      default:
        ipv4_address: 172.20.1.2

  percona-server:
    image: percona-server
    build: percona-server
    container_name: zenit_percona_server
    volumes:
      - data:/var/lib/mysql
    networks:
      default:
        ipv4_address: 172.20.1.3

  proxysql:
    image: proxysql
    build: proxysql
    container_name: zenit_proxysql
    networks:
      default:
        ipv4_address: 172.20.1.4

  sandbox:
    image: sandbox
    build:
      context: ../
      dockerfile: docker/sandbox/Dockerfile
    container_name: zenit_sandbox
    depends_on:
      - percona-server
    volumes:
      - data:/root/mysql/data
    networks:
      default:
        ipv4_address: 172.20.1.10

volumes:
  data:

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.1.0/24
