---
version: '3'

services:
  mysql-primary:
    image: percona-server-primary
    container_name: zenit_percona_server_primary
    build:
      context: ../
      dockerfile: docker/percona-server/Dockerfile
    environment:
      - SERVER_ID=1
    networks:
      default:
        ipv4_address: 172.20.1.3
  proxysql:
    image: proxysql/proxysql
    container_name: proxysql
    ports:
      - "3303:3306"
      - "6032:6032"
      - "6033:6033"
      - "6080:6080"
    volumes:
      -  ${PWD}/proxysql.cnf:/etc/proxysql.cnf
    networks:
      default:
        ipv4_address: 172.20.1.5

  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - "8083:8083"
      - "8086:8086"
      - "8090:8090"
    environment:
      - INFLUXDB_DATA_ENGINE=tsm1
      - INFLUXDB_REPORTING_DISABLED=false
    networks:
      default:
        ipv4_address: 172.20.1.6

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.1.0/24
